spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database : mysql
    hibernate.ddl-auto : update

logging:
  level:
    com.mutsasns.finalproject_kimmingyeong: debug

jwt:
  token:
    secret: "secretKey"